#include "tree_sitter/parser.h"

/*
 * External scanner for the QDoc tree-sitter grammar.
 *
 * Handles IMAGE_FILENAME and IMAGE_ALT_TEXT for the \image command.
 *
 * Why external? tree-sitter's extras rule consumes all whitespace (including
 * newlines) between tokens before the main lexer runs. This makes it
 * impossible to distinguish "alt text on the same line" from "text on the
 * next line" using a regular grammar rule or token.immediate (which is not
 * correctly code-generated by tree-sitter-cli@0.20.8).
 *
 * The external scanner is called with the raw input stream BEFORE extras are
 * consumed, so it can inspect whether the character immediately following the
 * filename is a space/tab (alt text on same line) or a newline (no alt text).
 *
 * IMAGE_FILENAME: skips leading horizontal whitespace, then consumes
 *   non-whitespace, non-backslash, non-asterisk characters as the filename.
 *
 * IMAGE_ALT_TEXT: fires only when the character immediately after the
 *   filename is a space or tab (same line). Skips that horizontal whitespace,
 *   then consumes characters up to the first newline, backslash, or asterisk.
 *   Leading whitespace is skipped (not included in the token text) so the
 *   node value is the clean alt text without surrounding spaces.
 */

typedef enum {
  IMAGE_FILENAME,
  IMAGE_ALT_TEXT,
} TokenType;

void *tree_sitter_qdoc_external_scanner_create() { return NULL; }
void tree_sitter_qdoc_external_scanner_destroy(void *payload) {}
void tree_sitter_qdoc_external_scanner_reset(void *payload) {}

unsigned tree_sitter_qdoc_external_scanner_serialize(void *payload, char *buffer) {
  return 0;
}

void tree_sitter_qdoc_external_scanner_deserialize(
    void *payload, const char *buffer, unsigned length) {}

bool tree_sitter_qdoc_external_scanner_scan(
    void *payload, TSLexer *lexer, const bool *valid_symbols) {

  if (valid_symbols[IMAGE_FILENAME]) {
    /* Skip leading horizontal whitespace (the space after \image). */
    while (lexer->lookahead == ' ' || lexer->lookahead == '\t') {
      lexer->advance(lexer, true);  /* skip=true: consume but don't include */
    }
    /* No filename if we hit a newline, backslash, asterisk, or EOF. */
    if (lexer->lookahead == '\n' || lexer->lookahead == '\r' ||
        lexer->lookahead == '\\' || lexer->lookahead == '*' ||
        lexer->lookahead == 0) {
      return false;
    }
    /* Consume the filename: everything up to whitespace or a delimiter. */
    while (lexer->lookahead != ' '  && lexer->lookahead != '\t' &&
           lexer->lookahead != '\n' && lexer->lookahead != '\r' &&
           lexer->lookahead != '\\' && lexer->lookahead != '*' &&
           lexer->lookahead != 0) {
      lexer->advance(lexer, false);  /* skip=false: include in token */
    }
    lexer->result_symbol = IMAGE_FILENAME;
    return true;
  }

  if (valid_symbols[IMAGE_ALT_TEXT]) {
    /*
     * Only fire when the character immediately following the filename is
     * horizontal whitespace — that means alt text is on the same line.
     * A newline here means there is no alt text.
     */
    if (lexer->lookahead != ' ' && lexer->lookahead != '\t') {
      return false;
    }
    /* Skip the horizontal whitespace (not included in the token text). */
    while (lexer->lookahead == ' ' || lexer->lookahead == '\t') {
      lexer->advance(lexer, true);
    }
    /* Nothing left on the line after the whitespace — no alt text. */
    if (lexer->lookahead == '\n' || lexer->lookahead == '\r' ||
        lexer->lookahead == '\\' || lexer->lookahead == '*' ||
        lexer->lookahead == 0) {
      return false;
    }
    /* Consume the alt text up to end of line. */
    while (lexer->lookahead != '\n' && lexer->lookahead != '\r' &&
           lexer->lookahead != '\\' && lexer->lookahead != '*' &&
           lexer->lookahead != 0) {
      lexer->advance(lexer, false);
    }
    lexer->result_symbol = IMAGE_ALT_TEXT;
    return true;
  }

  return false;
}
